builds:
  - binary: flow
    id: linux
    ldflags:
      - "-X main.version={{.version}}"
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: flow
    repository:
      owner: paldab
      name: homebrew-flow-cli
    commit_author:
      name: paldab
    directory: Formula
    homepage: https://github.com/paldab/flow-cli
    description: "Devops CLI to handle basic devops tasks"
    test: system "flow ip"

checksum:
  name_template: "checksums.sha256"

snapshot:
  name_template: "{{ .Tag }}-next"
