# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Devops CLI to handle basic devops tasks"
  homepage "https://github.com/Edens-Angel/flow-cli"
  version "0.2"

  on_macos do
    url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_darwin_all.tar.gz"
    sha256 "6f82cc3ce21dbc8ff991f706482d10f0e9675a512a956a88a22ee2158aa47842"

    def install
      bin.install "flow-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_linux_amd64.tar.gz"
      sha256 "fdbb5cbe8730ceb05ce10bd725f68a2387441d060385850972b72627eec1075d"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_linux_arm64.tar.gz"
      sha256 "81ab9eb0746b1f6459813aef2256771c6c9d11f696b6c1ee6fc76df648b11015"

      def install
        bin.install "flow"
      end
    end
  end

  test do
    system "flow ip"
  end
end
