# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Simple CLI to handle basic devops tasks"
  homepage "https://github.com/Edens-Angel/flow-cli"
  version "0.1"

  on_macos do
    url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.1/flow-cli_0.1_darwin_all.tar.gz"
    sha256 "4ec2d3b5f90411cc5ff96cb6d396a89c929470a2a2fbb7ce334b65c90f25b606"

    def install
      bin.install "flow-cli"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.1/flow-cli_0.1_linux_arm64.tar.gz"
      sha256 "15ecb2d7245cf4c8e94a6afc7530e85fa3bef80367d696124941af10bf17132c"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.1/flow-cli_0.1_linux_amd64.tar.gz"
      sha256 "4dc3974b1bdc2096e4ac30e17c119e9aefeda910bd09116853c4459706825fe5"

      def install
        bin.install "flow"
      end
    end
  end

  test do
    system "flow ip"
  end
end
