# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Devops CLI to handle basic devops tasks"
  homepage "https://github.com/Edens-Angel/flow-cli"
  version "0.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_darwin_arm64.tar.gz"
      sha256 "8a6b6aa26039c510d38ae586700c0a936520d9ac5d3997b8c4e972c9cd6403ab"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_darwin_amd64.tar.gz"
      sha256 "a8f1d5687bf45522f5ebd0b520632a89dc1c3b9c9c01fd0af72f6aaeb3b9c517"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_linux_arm64.tar.gz"
      sha256 "137e1143a261606ba7dfccee178579fac13561c6218d114894c17f45b14cf2f7"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Edens-Angel/flow-cli/releases/download/v0.2/flow-cli_0.2_linux_amd64.tar.gz"
      sha256 "0abd83fd7d6ec26ac6d7ee5e4c92e87e7f5f29044da15d87277a2620002439e2"

      def install
        bin.install "flow"
      end
    end
  end

  test do
    system "flow ip"
  end
end
